drop table answer if exists;

drop table delete_history if exists;

drop table question if exists;

drop table user if exists;

create table user (
    id bigint generated by default as identity,
    create_date timestamp,
    modified_date timestamp,
    email varchar(255),
    name varchar(255),
    password varchar(255),
    user_id varchar(20) not null,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    create_date timestamp,
    modified_date timestamp,
    contents clob,
    count_of_answer integer,
    deleted boolean not null,
    title varchar(255),
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    create_date timestamp,
    modified_date timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint generated by default as identity,
    content_id bigint,
    content_type varchar(255),
    create_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

alter table user 
    add constraint UK_a3imlf41l37utmxiquukk8ajc unique (user_id);

alter table answer 
    add constraint fk_answer_to_question 
    foreign key (question_id) 
    references question;

alter table answer 
    add constraint fk_answer_writer 
    foreign key (writer_id) 
    references user;

alter table delete_history 
    add constraint fk_deletehistory_to_user 
    foreign key (deleted_by_id) 
    references user;

alter table question 
    add constraint fk_question_writer 
    foreign key (writer_id) 
    references user;